name: nodeJs FE 
on: workflow_dispatch
jobs:
   building_FE:
     runs-on: ubuntu-latest
     steps:
        - name: print hello
          run: echo "HELLO"
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16.18.0'
        - name: Install dependencies
          run: npm install
        - uses: actions/setup-java@v4
          with:
           distribution: 'zulu' # See 'Supported distributions' for available options
           java-version: '8' 
        - run: java HelloWorldApp.java 
